[package]
name = "rusty-router-platform-linux"
version = "0.1.0"
authors = ["gazzasaur"]
edition = "2018"

[dependencies]
log = "0.4"
mockall = "0.9"

libc = "0.2"
async-trait = "0.1"
tokio = { version = "1.11", features = ["full"] }

nix = "0.21"
rand = "0.8"
chrono = "0.4"
anyhow = "1.0"
rtnetlink = "0.7"
thiserror = "1.0"
netlink-packet-core = "0.2"
netlink-packet-route = "0.7"
rusty-router-model = { path = "../rusty-router-model" }
netlink-sys = { version = "0.7", features = ["tokio_socket"] }

[dev-dependencies]
tokio-test = "0.4"
lazy_static = "1.4"
