[package]
name = "rusty-router-proto-ospfv2"
version = "0.1.0"
edition = "2018"

[dependencies]
rusty-router-proto-ip = { path = "../rusty-router-proto-ip" }
rusty-router-proto-common = { path = "../rusty-router-proto-common" }
