[package]
name = "rusty-router-model"
version = "0.1.0"
authors = ["gazzasaur"]
edition = "2018"

[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }
serde_json = "1.0"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
